title: Test xD
author: Jose
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
   Test de prueba para mostrar rangos de auto chess
# social links
twitter_username: J_velarde
github_username: Line77

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
