title: Titulo del sitio de prueba
author: Jose
email: Josevelarde00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Descripcion del sitio de prueba
# social links
twitter_username: J_velarde
github_username: Line77
# highlighter: rouge

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
