title: Test xD
author: Jose
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Test de prueba para mostrar rangos de auto chess
# social links
twitter_username: J_velarde
github_username: Line77
# highlighter: rouge

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
